services:
  mongo:
    image: mongo:4.4
    container_name: dnd_mongo
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_DB_NAME}
    ports:
      - '127.0.0.1:27017:27017' # Only accessible from localhost
    volumes:
      - mongo_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - backend
    ulimits:
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000

  web:
    build:
      context: .
      network: host
    container_name: dnd_web
    restart: unless-stopped
    ports:
      - '0.0.0.0:5000:5000' # Allow external access to Flask app
    environment:
      - MONGO_USER=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_PASS=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_DB=${MONGO_DB_NAME}
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - FLASK_ENV=production
      - SECRET_KEY=${SECRET_KEY}
    volumes:
      - ./logs:/app/logs
    networks:
      - backend
      - frontend
    ulimits:
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000
    depends_on:
      - mongo

networks:
  backend:
    internal: true # No external access for backend communication
  frontend:
    internal: false # Allow external access for web traffic

volumes:
  mongo_data:
    driver: local
