version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  mongo_loader:
    build: .
    depends_on:
      - mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: fakepassword
    entrypoint: ["/bin/sh", "-c", "sleep 10 && mongoimport --host mongodb --db gh_database --collection gh_collection --file /monsters.json --jsonArray"]

volumes:
  mongodb_data:
