services:
  mongo:
    image: mongo:latest
    container_name: dnd_mongo
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_DB_NAME}
    ports:
      - '127.0.0.1:27017:27017' # Only accessible from localhost
    volumes:
      - mongo_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - backend
    security_opt:
      - no-new-privileges:true
    ulimits:
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000

  web:
    build: .
    container_name: dnd_web
    restart: unless-stopped
    ports:
      - '127.0.0.1:5000:5000' # Flask app port
    environment:
      - MONGO_USER=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_PASS=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_DB=${MONGO_DB_NAME}
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - FLASK_ENV=production
      - SECRET_KEY=${SECRET_KEY}
    volumes:
      - ./logs:/app/logs
    networks:
      - backend
      - frontend
    security_opt:
      - no-new-privileges:true
    ulimits:
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000
    depends_on:
      - mongo

networks:
  backend:
    internal: true # No external access
  frontend:
    # This network will be connected to nginx

volumes:
  mongo_data:
    driver: local
