name: Deploy to Production

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Debug SSH key
        run: |
          echo "=== SSH Key Debug ==="
          echo "Key length: $(echo "${{ secrets.SSH_PRIVATE_KEY }}" | wc -l) lines"
          echo "First line: $(echo "${{ secrets.SSH_PRIVATE_KEY }}" | head -n 1)"
          echo "Last line: $(echo "${{ secrets.SSH_PRIVATE_KEY }}" | tail -n 1)"
          echo "=== End SSH Key Debug ==="

      - name: Setup WireGuard VPN
        run: |
          echo "=== Setting up WireGuard VPN ==="
          # Install WireGuard
          sudo apt-get update
          sudo apt-get install -y wireguard

          # Create WireGuard config
          sudo mkdir -p /etc/wireguard
          echo "${{ secrets.WIREGUARD_CONFIG }}" | sudo tee /etc/wireguard/wg0.conf > /dev/null
          sudo chmod 600 /etc/wireguard/wg0.conf

          # Start WireGuard
          sudo wg-quick up wg0

          # Wait for connection
          sleep 5

          # Show connection status
          sudo wg show
          echo "=== VPN Setup Complete ==="

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: |
            ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add known hosts
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts
          echo "=== Known Hosts ==="
          cat ~/.ssh/known_hosts
          echo "=== End Known Hosts ==="

      - name: Deploy to server
        run: |
          echo "=== SSH Agent Status ==="
          ssh-add -l
          echo "=== End SSH Agent Status ==="

          echo "=== Starting Deployment ==="
          ssh -v -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} '
            echo "Creating backup of MongoDB data..."
            docker exec dnd_mongo mongodump --out /backup/$(date +%Y%m%d_%H%M%S)
            
            echo "Pulling latest changes..."
            cd /home/kasu/grim-hallow-data
            git pull origin main
            
            echo "Updating containers..."
            docker-compose -f docker-compose.prod.yml up -d --build
            
            echo "Cleaning up old backups (keeping last 5)..."
            ls -t /backup | tail -n +6 | xargs -I {} rm -rf /backup/{}
            
            echo "Pruning unused Docker images..."
            docker image prune -f
          '
          if [ $? -ne 0 ]; then
            echo "=== SSH Environment ==="
            echo "SSH_AUTH_SOCK: $SSH_AUTH_SOCK"
            echo "SSH_AGENT_PID: $SSH_AGENT_PID"
            echo "=== End SSH Environment ==="
            exit 1
          fi

      - name: Cleanup VPN
        if: always()
        run: |
          echo "=== Cleaning up VPN ==="
          sudo wg-quick down wg0
          echo "=== VPN Cleanup Complete ==="
