name: Deploy to Production

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Debug SSH key
        run: |
          echo "=== SSH Key Debug ==="
          echo "Key length: $(echo "${{ secrets.SSH_PRIVATE_KEY }}" | wc -l) lines"
          echo "First line: $(echo "${{ secrets.SSH_PRIVATE_KEY }}" | head -n 1)"
          echo "Last line: $(echo "${{ secrets.SSH_PRIVATE_KEY }}" | tail -n 1)"
          echo "=== End SSH Key Debug ==="

      - name: Setup WireGuard VPN
        run: |
          echo "=== Setting up WireGuard VPN ==="
          # Install WireGuard
          sudo apt-get update
          sudo apt-get install -y wireguard

          # Create WireGuard config
          sudo mkdir -p /etc/wireguard
          echo "${{ secrets.WIREGUARD_CONFIG }}" | sudo tee /etc/wireguard/wg0.conf > /dev/null
          sudo chmod 600 /etc/wireguard/wg0.conf

          # Start WireGuard
          sudo wg-quick up wg0

          # Wait for connection
          sleep 5

          # Show connection status
          sudo wg show
          echo "=== VPN Setup Complete ==="

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: |
            ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add known hosts
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts
          echo "=== Known Hosts ==="
          cat ~/.ssh/known_hosts
          echo "=== End Known Hosts ==="

      - name: Deploy to server
        run: |
          echo "=== SSH Agent Status ==="
          ssh-add -l
          echo "=== End SSH Agent Status ==="

          echo "=== Starting Deployment ==="
          ssh -v -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} '
            echo "=== Checking server setup ==="
            
            # Check if project directory exists
            if [ ! -d "/home/${{ secrets.SSH_USER }}/monster-data" ]; then
              echo "Project directory not found. Please run the setup script first."
              exit 1
            fi
            
            cd /home/${{ secrets.SSH_USER }}/monster-data
            
            # Check if git repository exists
            if [ ! -d ".git" ]; then
              echo "Git repository not found. Cloning..."
              git clone https://github.com/your-username/monster-data.git .
            fi
            
            # Check Docker permissions
            if ! docker info > /dev/null 2>&1; then
              echo "Docker permission denied. Please ensure user is in docker group."
              echo "Run: newgrp docker"
              exit 1
            fi
            
            # Create backup directory if it doesn't exist
            mkdir -p /home/${{ secrets.SSH_USER }}/backup
            
            echo "=== Creating backup of MongoDB data ==="
            if docker ps | grep -q dnd_mongo; then
              docker exec dnd_mongo mongodump --out /backup/$(date +%Y%m%d_%H%M%S) || echo "Backup failed, continuing..."
            else
              echo "MongoDB container not running, skipping backup"
            fi
            
            echo "=== Pulling latest changes ==="
            git pull origin main
            
            echo "=== Updating containers ==="
            docker-compose -f docker-compose.prod.yml up -d --build
            
            echo "=== Cleaning up old backups (keeping last 5) ==="
            ls -t /backup | tail -n +6 | xargs -I {} rm -rf /backup/{} 2>/dev/null || true
            
            echo "=== Pruning unused Docker images ==="
            docker image prune -f
            
            echo "=== Deployment Complete ==="
          '
          if [ $? -ne 0 ]; then
            echo "=== SSH Environment ==="
            echo "SSH_AUTH_SOCK: $SSH_AUTH_SOCK"
            echo "SSH_AGENT_PID: $SSH_AGENT_PID"
            echo "=== End SSH Environment ==="
            exit 1
          fi

      - name: Cleanup VPN
        if: always()
        run: |
          echo "=== Cleaning up VPN ==="
          sudo wg-quick down wg0
          echo "=== VPN Cleanup Complete ==="
